import java.awt.*;
import java.awt.event.*;
import javax.swing.*; 
import java.util.ArrayList;
import java.util.Random; 
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.*; 
/**
 * Write a description of class CSP_Game here.
 *
 * @author (your name)
 * @version (a version number or a date)
 */
public class CSP_Game
{
    /**
     * Create a constructor to make the game frame
     * This is done when then corresponding button is clicked in startFrame
     * Constructs a new frame that's initially invisible
     * Throws a HeadlessException
     */
    public CSP_Game() throws HeadlessException
    {
    }
    public void run()
    {
        //create the frame
        JFrame cspFrame = new JFrame("Caribbean Stud Poker");
        
        //create a button to return to the previous page
        JButton close = new JButton("Close Game");
        close.setFont(new Font("Arial", Font.PLAIN, 35)); 
        /**
         * When the close button is clicked, have the program closed.
         * Add an action listener and use an anonymous class to 
         * implement the ActionListener interface
         * Have the method actionPerformed(ActionEvent name) called and set what 
         * needs to be done in the method
         * For this, call the startFrame constructor, then the run method to show the
         * start frame, then dispose of the CSP frame
         * @param the implicit parameter of this type of call is the button associated
         * with it 
         */
        close.addActionListener(new ActionListener()
        {
           public void actionPerformed(ActionEvent exit)
           {
               startFrame returnStart = new startFrame();
               returnStart.run();
               cspFrame.dispose(); 
           }
        });
        //make a button for drawing cards to deal for the current hand 
        //make an arraylist to hold the values for a standard deck of cards
        JButton drawCards = new JButton("DrawCards"); 
        drawCards.setFont(new Font("Arial", Font.PLAIN, 35)); 
        ArrayList<String> cardDeck = new ArrayList<String>(); 
        //hearts
        cardDeck.add("AH");
        cardDeck.add("2H");
        cardDeck.add("3H");
        cardDeck.add("4H");
        cardDeck.add("5H");
        cardDeck.add("6H");
        cardDeck.add("7H");
        cardDeck.add("8H");
        cardDeck.add("9H");
        cardDeck.add("10H");
        cardDeck.add("JH");
        cardDeck.add("QH");
        cardDeck.add("KH"); 
        //spades 
        cardDeck.add("AS");
        cardDeck.add("2S");
        cardDeck.add("3S");
        cardDeck.add("4S");
        cardDeck.add("5S");
        cardDeck.add("6S");
        cardDeck.add("7S");
        cardDeck.add("8S");
        cardDeck.add("9S");
        cardDeck.add("10S");
        cardDeck.add("JS");
        cardDeck.add("QS");
        cardDeck.add("KS");
        //diamonds 
        cardDeck.add("AD");
        cardDeck.add("2D");
        cardDeck.add("3D");
        cardDeck.add("4D");
        cardDeck.add("5D");
        cardDeck.add("6D");
        cardDeck.add("7D");
        cardDeck.add("8D");
        cardDeck.add("9D");
        cardDeck.add("10D");
        cardDeck.add("JD");
        cardDeck.add("QD");
        cardDeck.add("KD");
        //clubs 
        cardDeck.add("AC");
        cardDeck.add("2C");
        cardDeck.add("3C");
        cardDeck.add("4C");
        cardDeck.add("5C");
        cardDeck.add("6C");
        cardDeck.add("7C");
        cardDeck.add("8C");
        cardDeck.add("9C");
        cardDeck.add("10C");
        cardDeck.add("JC");
        cardDeck.add("QC");
        cardDeck.add("KC");
        //add an action listener to perform an action when the button is clicked 
        drawCards.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent draw)
            {
                //use a random number generator to generate numbers between 0 and 51
                //these numbers will reference elements in the arraylist made above 
                Random rand = new Random(); 
                //use an int value to represent the max number generated by the rand below 
                int n = 51;
                String playerHand = "";
                String dealerHand = ""; 
                //for loop to deal the dealer his hand
                for(int i = 0; i < 5; i++)
                {
                    //generate the random number
                    int cardNum = rand.nextInt(n) + 0;
                    //add the card to the dealer's hand 
                    dealerHand += cardDeck.get(cardNum);
                    //remove the card from the arraylist 
                    cardDeck.remove(cardNum);
                    //reduce the max number made by the random number generator 
                    n--; 
                }
                for(int j = 0; j < 5; j++)
                {
                    //generate the random number
                    int cardNum2 = rand.nextInt(n) + 0;
                    //add the card to the player's hand 
                    playerHand += cardDeck.get(cardNum2);
                    //remove the card from the arraylist 
                    cardDeck.remove(cardNum2); 
                    //reduce the max number made by the random number generator 
                    n--;
                }
                
                /**
                 * Create a JTextArea to display text so it is easier to read 
                 * than the default text size for the JOptionPane
                 * set editable, opaque, text, and font to make it easy to read
                 * @method setEditable makes it so the user can't edit it
                 * @method setOpague(false) sets the background of the 
                 *         text area to clear
                 * @method setText adds text output to the text area
                 * @method setFont sets the font of the text area
                 */
                
                JTextArea outputText = new JTextArea();
                outputText.setEditable(false);
                outputText.setOpaque(false);
                outputText.setText("Player Hand: " + playerHand + "\n" + "Dealer Hand: " + dealerHand);
                outputText.setFont(outputText.getFont().deriveFont(25f));
                
                JOptionPane.showMessageDialog(cspFrame, outputText, "Cards Have Been Dealt", JOptionPane.INFORMATION_MESSAGE);
                //sets the drawCards button to invisible once it has been clicked
                //when clicked a second time, an error occured
                //to solve this, whenever the current hand has been dealt, make the button invisible 
                drawCards.setVisible(false); 
            }
        });
        /**
         * Set layout of the frame
         * Then, add each part of the frame
         */
        cspFrame.setLayout(new GridLayout(10, 1));
        cspFrame.add(drawCards); 
        cspFrame.add(close);
        /**
         * @method setDefaultCloseOperation(), used to close the program if 
         * the window of the program is closed, so as to avoid the program 
         * continuing to run after user closes the window
         * use the pack() to set the size of the frame to fit all of its contents
         * then, set the frame to visible
         */
        cspFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cspFrame.pack();
        cspFrame.setVisible(true); 
    }
}
