/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 

//import sun.audio.*;
import javax.swing.JFrame;
/**
 *
 * @author dnguy
 */
public class cariStudPoker extends JFrame {
    public cariStudPoker() {
        initComponents();
        setTitle("Caribbean Stud Poker");
        setSize(1520,1010);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cardBack = new javax.swing.JLabel();
        sA = new javax.swing.JLabel();
        sK = new javax.swing.JLabel();
        sQ = new javax.swing.JLabel();
        sJ = new javax.swing.JLabel();
        s10 = new javax.swing.JLabel();
        s9 = new javax.swing.JLabel();
        s8 = new javax.swing.JLabel();
        s7 = new javax.swing.JLabel();
        s6 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        cA = new javax.swing.JLabel();
        cK = new javax.swing.JLabel();
        cQ = new javax.swing.JLabel();
        cJ = new javax.swing.JLabel();
        c10 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        d9 = new javax.swing.JLabel();
        d10 = new javax.swing.JLabel();
        dJ = new javax.swing.JLabel();
        dQ = new javax.swing.JLabel();
        dK = new javax.swing.JLabel();
        dA = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        h4 = new javax.swing.JLabel();
        h5 = new javax.swing.JLabel();
        h6 = new javax.swing.JLabel();
        h7 = new javax.swing.JLabel();
        h8 = new javax.swing.JLabel();
        h9 = new javax.swing.JLabel();
        h10 = new javax.swing.JLabel();
        hJ = new javax.swing.JLabel();
        hQ = new javax.swing.JLabel();
        hK = new javax.swing.JLabel();
        hA = new javax.swing.JLabel();
        wins = new java.awt.Label();
        losses = new java.awt.Label();
        winLoseRatio = new java.awt.Label();
        cardPlace1 = new javax.swing.JLabel();
        cardPlace2 = new javax.swing.JLabel();
        cardPlace3 = new javax.swing.JLabel();
        cardPlace4 = new javax.swing.JLabel();
        cardPlace5 = new javax.swing.JLabel();
        cardPlace6 = new javax.swing.JLabel();
        cardPlace7 = new javax.swing.JLabel();
        cardPlace8 = new javax.swing.JLabel();
        cardPlace9 = new javax.swing.JLabel();
        cardPlace10 = new javax.swing.JLabel();
        anteButton = new javax.swing.JLabel();
        foldButton = new javax.swing.JLabel();
        raiseButton = new javax.swing.JLabel();
        playButton = new javax.swing.JLabel();
        jackButton = new javax.swing.JLabel();
        finButton = new javax.swing.JLabel();
        betButton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        cardBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backCard.png"))); // NOI18N
        cardBack.setText("jLabel1");
        getContentPane().add(cardBack);
        cardBack.setBounds(50, 410, 180, 251);

        sA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spadeA.jpg"))); // NOI18N
        sA.setText("jLabel1");
        getContentPane().add(sA);
        sA.setBounds(260, 410, 180, 250);

        sK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spadeK.jpg"))); // NOI18N
        sK.setText("jLabel1");
        getContentPane().add(sK);
        sK.setBounds(50, 410, 180, 250);

        sQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spadeQ.jpg"))); // NOI18N
        sQ.setText("jLabel1");
        getContentPane().add(sQ);
        sQ.setBounds(50, 410, 180, 250);

        sJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spadeJ.jpg"))); // NOI18N
        sJ.setText("jLabel1");
        getContentPane().add(sJ);
        sJ.setBounds(50, 410, 180, 250);

        s10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade10.jpg"))); // NOI18N
        s10.setText("jLabel1");
        getContentPane().add(s10);
        s10.setBounds(50, 410, 180, 250);

        s9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade9.jpg"))); // NOI18N
        s9.setText("jLabel1");
        getContentPane().add(s9);
        s9.setBounds(50, 410, 180, 250);

        s8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade8.jpg"))); // NOI18N
        s8.setText("jLabel1");
        getContentPane().add(s8);
        s8.setBounds(50, 410, 180, 251);

        s7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade7.jpg"))); // NOI18N
        s7.setText("jLabel1");
        getContentPane().add(s7);
        s7.setBounds(50, 410, 180, 251);

        s6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade6.jpg"))); // NOI18N
        s6.setText("jLabel1");
        getContentPane().add(s6);
        s6.setBounds(50, 410, 180, 250);

        s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade5.jpg"))); // NOI18N
        s5.setText("jLabel1");
        getContentPane().add(s5);
        s5.setBounds(50, 410, 180, 250);

        s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade4.jpg"))); // NOI18N
        s4.setText("jLabel1");
        getContentPane().add(s4);
        s4.setBounds(50, 410, 180, 250);

        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade3.jpg"))); // NOI18N
        s3.setText("jLabel1");
        getContentPane().add(s3);
        s3.setBounds(50, 410, 180, 250);

        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spade2.jpg"))); // NOI18N
        s2.setText("jLabel1");
        getContentPane().add(s2);
        s2.setBounds(50, 410, 180, 250);

        cA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spadeA.jpg"))); // NOI18N
        cA.setText("jLabel14");
        getContentPane().add(cA);
        cA.setBounds(50, 410, 180, 250);

        cK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clubK.jpg"))); // NOI18N
        cK.setText("jLabel1");
        getContentPane().add(cK);
        cK.setBounds(50, 410, 180, 250);

        cQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clubQ.jpg"))); // NOI18N
        cQ.setText("jLabel1");
        getContentPane().add(cQ);
        cQ.setBounds(50, 410, 180, 250);

        cJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clubJ.jpg"))); // NOI18N
        cJ.setText("jLabel1");
        getContentPane().add(cJ);
        cJ.setBounds(50, 410, 180, 250);

        c10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club10.png"))); // NOI18N
        c10.setText("jLabel1");
        getContentPane().add(c10);
        c10.setBounds(50, 410, 180, 250);

        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club9.jpg"))); // NOI18N
        c9.setText("jLabel1");
        getContentPane().add(c9);
        c9.setBounds(50, 410, 180, 250);

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club8.jpg"))); // NOI18N
        c8.setText("jLabel1");
        getContentPane().add(c8);
        c8.setBounds(50, 410, 180, 250);

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club7.jpg"))); // NOI18N
        c7.setText("jLabel1");
        getContentPane().add(c7);
        c7.setBounds(50, 410, 180, 250);

        c6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club6.jpg"))); // NOI18N
        c6.setText("jLabel1");
        getContentPane().add(c6);
        c6.setBounds(50, 410, 180, 251);

        c5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club5.jpg"))); // NOI18N
        c5.setText("jLabel1");
        getContentPane().add(c5);
        c5.setBounds(50, 410, 180, 250);

        c4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club4.jpg"))); // NOI18N
        c4.setText("jLabel1");
        getContentPane().add(c4);
        c4.setBounds(50, 410, 180, 250);

        c3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club3.jpg"))); // NOI18N
        c3.setText("jLabel1");
        getContentPane().add(c3);
        c3.setBounds(50, 410, 180, 250);

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/club2.jpg"))); // NOI18N
        c2.setText("jLabel1");
        getContentPane().add(c2);
        c2.setBounds(50, 410, 180, 250);

        d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam2.jpg"))); // NOI18N
        d2.setText("jLabel1");
        getContentPane().add(d2);
        d2.setBounds(50, 410, 180, 250);

        d3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam3.jpg"))); // NOI18N
        d3.setText("jLabel1");
        getContentPane().add(d3);
        d3.setBounds(50, 410, 180, 251);

        d4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam4.jpg"))); // NOI18N
        d4.setText("jLabel1");
        getContentPane().add(d4);
        d4.setBounds(50, 410, 180, 251);

        d5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam5.jpg"))); // NOI18N
        d5.setText("jLabel1");
        getContentPane().add(d5);
        d5.setBounds(50, 410, 180, 250);

        d6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam6.jpg"))); // NOI18N
        d6.setText("jLabel1");
        getContentPane().add(d6);
        d6.setBounds(50, 410, 180, 250);

        d7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam7.jpg"))); // NOI18N
        d7.setText("jLabel1");
        getContentPane().add(d7);
        d7.setBounds(50, 410, 180, 250);

        d8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam8.jpg"))); // NOI18N
        d8.setText("jLabel1");
        getContentPane().add(d8);
        d8.setBounds(50, 410, 180, 250);

        d9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam9.jpg"))); // NOI18N
        d9.setText("jLabel1");
        getContentPane().add(d9);
        d9.setBounds(50, 410, 180, 250);

        d10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diam10.jpg"))); // NOI18N
        d10.setText("jLabel1");
        getContentPane().add(d10);
        d10.setBounds(50, 410, 180, 251);

        dJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diamJ.jpg"))); // NOI18N
        dJ.setText("jLabel1");
        getContentPane().add(dJ);
        dJ.setBounds(50, 410, 180, 250);

        dQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diamQ.jpg"))); // NOI18N
        dQ.setText("jLabel1");
        getContentPane().add(dQ);
        dQ.setBounds(50, 410, 180, 250);

        dK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diamK.jpg"))); // NOI18N
        dK.setText("jLabel1");
        getContentPane().add(dK);
        dK.setBounds(50, 410, 180, 250);

        dA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diamA.jpg"))); // NOI18N
        dA.setText("jLabel1");
        getContentPane().add(dA);
        dA.setBounds(50, 410, 180, 250);

        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart2.jpg"))); // NOI18N
        h2.setText("jLabel1");
        getContentPane().add(h2);
        h2.setBounds(50, 410, 180, 250);

        h3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart3.jpg"))); // NOI18N
        h3.setText("jLabel1");
        getContentPane().add(h3);
        h3.setBounds(50, 410, 180, 250);

        h4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart4.jpg"))); // NOI18N
        h4.setText("jLabel1");
        getContentPane().add(h4);
        h4.setBounds(50, 410, 180, 250);

        h5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart5.jpg"))); // NOI18N
        h5.setText("jLabel1");
        getContentPane().add(h5);
        h5.setBounds(50, 410, 180, 250);

        h6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart6.jpg"))); // NOI18N
        h6.setText("jLabel1");
        getContentPane().add(h6);
        h6.setBounds(50, 410, 180, 251);

        h7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart7.jpg"))); // NOI18N
        h7.setText("jLabel1");
        getContentPane().add(h7);
        h7.setBounds(50, 410, 180, 251);

        h8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart8.jpg"))); // NOI18N
        h8.setText("jLabel1");
        getContentPane().add(h8);
        h8.setBounds(50, 410, 180, 250);

        h9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart9.jpg"))); // NOI18N
        h9.setText("jLabel1");
        getContentPane().add(h9);
        h9.setBounds(50, 410, 180, 250);

        h10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart10.jpg"))); // NOI18N
        h10.setText("jLabel1");
        getContentPane().add(h10);
        h10.setBounds(50, 410, 180, 250);

        hJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heartJ.jpg"))); // NOI18N
        hJ.setText("jLabel1");
        getContentPane().add(hJ);
        hJ.setBounds(50, 410, 180, 251);

        hQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heartQ.jpg"))); // NOI18N
        hQ.setText("jLabel1");
        getContentPane().add(hQ);
        hQ.setBounds(50, 410, 180, 251);

        hK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heartK.jpg"))); // NOI18N
        hK.setText("jLabel1");
        getContentPane().add(hK);
        hK.setBounds(50, 410, 180, 251);

        hA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heartA.jpg"))); // NOI18N
        hA.setText("jLabel1");
        getContentPane().add(hA);
        hA.setBounds(50, 410, 180, 250);

        wins.setText("Wins:");
        getContentPane().add(wins);
        wins.setBounds(1280, 20, 70, 20);

        losses.setText("Losses:");
        getContentPane().add(losses);
        losses.setBounds(1370, 20, 80, 20);

        winLoseRatio.setText("Win/Lose Ratio:");
        getContentPane().add(winLoseRatio);
        winLoseRatio.setBounds(1280, 50, 170, 20);

        cardPlace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace1.setText("jLabel2");
        getContentPane().add(cardPlace1);
        cardPlace1.setBounds(140, 90, 220, 290);

        cardPlace2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace2.setText("jLabel2");
        getContentPane().add(cardPlace2);
        cardPlace2.setBounds(390, 90, 220, 280);

        cardPlace3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace3.setText("jLabel2");
        getContentPane().add(cardPlace3);
        cardPlace3.setBounds(640, 90, 220, 280);

        cardPlace4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace4.setText("jLabel2");
        getContentPane().add(cardPlace4);
        cardPlace4.setBounds(890, 90, 220, 280);

        cardPlace5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace5.setText("jLabel2");
        getContentPane().add(cardPlace5);
        cardPlace5.setBounds(1140, 90, 220, 280);

        cardPlace6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace6.setText("jLabel2");
        getContentPane().add(cardPlace6);
        cardPlace6.setBounds(140, 680, 220, 290);

        cardPlace7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace7.setText("jLabel2");
        getContentPane().add(cardPlace7);
        cardPlace7.setBounds(390, 690, 220, 280);

        cardPlace8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace8.setText("jLabel2");
        getContentPane().add(cardPlace8);
        cardPlace8.setBounds(650, 690, 220, 280);

        cardPlace9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace9.setText("jLabel2");
        getContentPane().add(cardPlace9);
        cardPlace9.setBounds(900, 690, 220, 280);

        cardPlace10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cardplace.jpg"))); // NOI18N
        cardPlace10.setText("jLabel2");
        getContentPane().add(cardPlace10);
        cardPlace10.setBounds(1150, 690, 220, 280);

        anteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anteButton.png"))); // NOI18N
        anteButton.setText("jLabel1");
        getContentPane().add(anteButton);
        anteButton.setBounds(1230, 520, 120, 60);

        foldButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foldButton.png"))); // NOI18N
        foldButton.setText("jLabel12");
        getContentPane().add(foldButton);
        foldButton.setBounds(1230, 470, 120, 50);

        raiseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/raiseButton.png"))); // NOI18N
        raiseButton.setText("jLabel13");
        raiseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raiseButtonMouseClicked(evt);
            }
        });
        getContentPane().add(raiseButton);
        raiseButton.setBounds(1230, 410, 120, 60);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playButton.png"))); // NOI18N
        playButton.setText("jLabel1");
        getContentPane().add(playButton);
        playButton.setBounds(1230, 580, 120, 60);

        jackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jackButton.png"))); // NOI18N
        jackButton.setText("jLabel1");
        getContentPane().add(jackButton);
        jackButton.setBounds(1360, 500, 120, 50);

        finButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/finButton.png"))); // NOI18N
        finButton.setText("jLabel1");
        getContentPane().add(finButton);
        finButton.setBounds(1360, 560, 120, 50);

        betButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/betButton.png"))); // NOI18N
        betButton.setText("jLabel1");
        getContentPane().add(betButton);
        betButton.setBounds(1360, 440, 120, 50);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wood_texture_by_pabloalvin.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 1520, 1010);

        pack();
    }// </editor-fold>                        

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {                                        

    }                                       

    /**
     * When raise button is clicked
     * @param evt 
     */
    private void raiseButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
    
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
        // Constructs cards suit, faceName, and faceValue
    Card s2 = new Card("spades", "two", 2);
    Card sA = new Card("spades", "ace", 14);
    
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cariStudPoker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel anteButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel betButton;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel cA;
    private javax.swing.JLabel cJ;
    private javax.swing.JLabel cK;
    private javax.swing.JLabel cQ;
    private javax.swing.JLabel cardBack;
    private javax.swing.JLabel cardPlace1;
    private javax.swing.JLabel cardPlace10;
    private javax.swing.JLabel cardPlace2;
    private javax.swing.JLabel cardPlace3;
    private javax.swing.JLabel cardPlace4;
    private javax.swing.JLabel cardPlace5;
    private javax.swing.JLabel cardPlace6;
    private javax.swing.JLabel cardPlace7;
    private javax.swing.JLabel cardPlace8;
    private javax.swing.JLabel cardPlace9;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private javax.swing.JLabel dA;
    private javax.swing.JLabel dJ;
    private javax.swing.JLabel dK;
    private javax.swing.JLabel dQ;
    private javax.swing.JLabel finButton;
    private javax.swing.JLabel foldButton;
    private javax.swing.JLabel h10;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    private javax.swing.JLabel h9;
    private javax.swing.JLabel hA;
    private javax.swing.JLabel hJ;
    private javax.swing.JLabel hK;
    private javax.swing.JLabel hQ;
    private javax.swing.JLabel jackButton;
    private java.awt.Label losses;
    private javax.swing.JLabel playButton;
    private javax.swing.JLabel raiseButton;
    private javax.swing.JLabel s10;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    private javax.swing.JLabel s6;
    private javax.swing.JLabel s7;
    private javax.swing.JLabel s8;
    private javax.swing.JLabel s9;
    private javax.swing.JLabel sA;
    private javax.swing.JLabel sJ;
    private javax.swing.JLabel sK;
    private javax.swing.JLabel sQ;
    private java.awt.Label winLoseRatio;
    private java.awt.Label wins;
    // End of variables declaration                   
}
